apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ask-chatgpt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cyrip/ask-chatgpt.git'
    targetRevision: HEAD
    path: dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ask-chatgpt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true